const locale = [
  {
    en: 'Earning',
    id: 'Pendapatan',
    ar: 'الأرباح',
    fr: 'Gagner',
  },
  {
    en: 'Earning Summary',
    id: 'Ringkasan Pendapatan',
    ar: 'ملخص الأرباح',
    fr: 'Résumé des gains',
  },
  {
    en: 'Today',
    id: 'Hari ini',
    ar: 'اليوم',
    fr: "Aujourd'hui",
  },
  {
    en: 'Details',
    id: 'Rincian',
    ar: 'تفاصيل',
    fr: 'Détails',
  },
  {
    en: 'Order Completed',
    id: 'Pesanan Selesai',
    ar: 'تم الانتهاء من الطلب',
    fr: 'Commande terminée',
  },
  {
    en: 'View Order History',
    id: 'Lihat Riwayat Pesanan',
    ar: 'عرض سجل الطلبات',
    fr: "Voir l'historique des commandes",
  },
  {
    en: 'Under Development',
    id: 'Dalam Pengembangan',
    ar: 'تحت التطوير',
    fr: 'En développement',
  },
  {
    en: 'Withdrawal',
    id: 'Penarikan',
    ar: 'سحب',
    fr: 'Retrait',
  },
  {
    en: 'Top Up',
    id: 'Isi Saldo',
    ar: 'شحن الرصيد',
    fr: 'Recharger',
  },
  {
    en: 'Transaction',
    id: 'Transaksi',
    ar: 'المعاملات',
    fr: 'Transaction',
  },
  {
    en: 'Performance',
    id: 'Kinerja',
    ar: 'أداء',
    fr: 'Performance',
  },
  {
    en: 'from',
    id: 'dari',
    ar: 'من',
    fr: 'de',
  },
  {
    en: 'order',
    id: 'pesanan',
    ar: 'طلب',
    fr: 'commande',
  },
  {
    en: 'Point',
    id: 'Poin',
    ar: 'نقطة',
    fr: 'Point',
  },
  {
    en: 'Order History',
    id: 'Riwayat Pesanan',
    ar: 'سجل الطلبات',
    fr: 'Historique des commandes',
  },
  {
    en: 'All',
    id: 'Semua',
    ar: 'الكل',
    fr: 'Tout',
  },
  {
    en: 'Last 7 Days',
    id: '7 Hari Terakhir',
    ar: 'آخر 7 أيام',
    fr: 'Les 7 derniers jours',
  },
  {
    en: 'Last 30 Days',
    id: '30 Hari Terakhir',
    ar: 'آخر 30 يومًا',
    fr: 'Les 30 derniers jours',
  },
  {
    en: 'Last 14 Days',
    id: '14 Hari Terakhir',
    ar: 'آخر 14 يومًا',
    fr: 'Les 14 derniers jours',
  },
  {
    en: 'Earning Details',
    id: 'Rincian Pendapatan',
    ar: 'تفاصيل الأرباح',
    fr: 'Détails des gains',
  },
  {
    en: 'Total Income',
    id: 'Pendapatan Total',
    ar: 'إجمالي الدخل',
    fr: 'Revenu total',
  },
  {
    en: 'Income Detail',
    id: 'Detail Pendapatan',
    ar: 'تفاصيل الدخل',
    fr: 'Détail des revenus',
  },
  {
    en: 'Trip',
    id: 'Perjalanan',
    ar: 'رحلة',
    fr: 'Voyage',
  },
  {
    en: 'Incentive',
    id: 'Insentif',
    ar: 'الحوافز',
    fr: 'Incentive',
  },
  {
    en: 'Customer Tip',
    id: 'Tip Pelanggan',
    ar: 'نصيحة العميل',
    fr: 'Astuce client',
  },
  {
    en: 'Balance',
    id: 'Saldo',
    ar: 'توازن',
    fr: 'Équilibre',
  },
  {
    en: 'Amount',
    id: 'Jumlah',
    ar: 'كمية',
    fr: 'Montant',
  },
  {
    en: 'Warning: ',
    id: 'Peringatan: ',
    ar: 'تحذير: ',
    fr: 'Attention: ',
  },
  {
    en: 'Withdrawal amount exceeded the deposit limit balance or Insufficient Fund',
    id: 'Jumlah penarikan melebihi batas saldo deposit atau Dana Tidak Cukup',
    ar: 'تجاوز المبلغ المسحوب حد رصيد الودائع أو رصيد غير كافي',
    fr: 'Le montant du retrait a dépassé la limite de solde de dépôt ou le solde est insuffisant',
  },
  {
    en: 'Please Note: ',
    id: 'Harap Perhatikan: ',
    ar: 'يرجى ملاحظة: ',
    fr: 'Veuillez noter: ',
  },
  {
    en: 'Minimum amount withdrawal for driver is',
    id: 'Jumlah penarikan minimum untuk driver adalah',
    ar: 'الحد الأدنى للسحب للسائق هو',
    fr: 'Le montant minimum de retrait pour le conducteur est',
  },
  {
    en: 'Your withdrawal process failed',
    id: 'Proses penarikan Anda gagal',
    ar: 'فشلت عملية السحب الخاصة بك',
    fr: 'Votre processus de retrait a échoué',
  },
  {
    en: 'Something went wrong at our end. Don’t worry, it’s not you, it’s us. Sorry about that.',
    id: 'Ada yang tidak beres di pihak kami. Jangan khawatir, ini bukan Anda, ini kami. Maaf soal itu.',
    ar: 'حدث خطأ ما في نهايتنا. لا تقلق ، لست أنت - نحن. اسف بشأن ذلك.',
    fr: 'Quelque chose sest mal passé de notre côté. Ne vous inquiétez pas, ce nest pas vous cest nous. Désolé pour ça.',
  },
  {
    en: 'Withdrawal to',
    id: 'Penarikan ke',
    ar: 'سحب إلى',
    fr: 'Retrait à',
  },
  {
    en: 'Try Again',
    id: 'Coba lagi',
    ar: 'حاول ثانية',
    fr: 'Essayer à nouveau',
  },
  {
    en: 'Bank Account',
    id: 'Rekening Bank',
    ar: 'حساب بنكي',
    fr: 'Compte bancaire',
  },
  {
    en: 'Withdraw',
    id: 'Tarik',
    ar: 'سحب',
    fr: 'Retirer',
  },
  {
    en: 'Successfull',
    id: 'Berhasil',
    ar: 'ناجح',
    fr: 'Succès',
  },
  {
    en: 'Your withdrawal process have been successfull !',
    id: 'Proses penarikan Anda telah berhasil!',
    ar: 'تمت عملية السحب بنجاح!',
    fr: 'Votre processus de retrait a été un succès!',
  },
  {
    en: 'We already got your withdrawal request, we need maximum 24 hours to process it.',
    id: 'Kami sudah mendapatkan permintaan penarikan Anda, kami membutuhkan maksimal 24 jam untuk memprosesnya.',
    ar: 'لقد تلقينا بالفعل طلب السحب الخاص بك ، ونحتاج إلى 24 ساعة كحد أقصى لمعالجته.',
    fr: 'Nous avons déjà reçu votre demande de retrait, nous avons besoin de maximum 24 heures pour la traiter.',
  },
  {
    en: 'Continue',
    id: 'Lanjutkan',
    ar: 'استمر',
    fr: 'Continuer',
  },
  {
    en: 'Top Up',
    id: 'Isi Ulang',
    ar: 'شحن',
    fr: 'Recharger',
  },
  {
    en: 'Virtual Account No.',
    id: 'No. Virtual Account',
    ar: 'رقم الحساب الافتراضي',
    fr: 'Numéro de compte virtuel',
  },
  {
    en: 'Copy',
    id: 'Salin',
    ar: 'نسخ',
    fr: 'Copier',
  },
  {
    en: 'Payment Method',
    id: 'Metode Pembayaran',
    ar: 'طريقة الدفع او السداد',
    fr: 'Mode de paiement',
  },
  {
    en: 'Done',
    id: 'Selesai',
    ar: 'تم',
    fr: 'Terminé',
  },
];

export default locale;
