const locale = [
  {
    en: 'Let’s you in',
    id: 'Ayo masuk',
    ar: 'يكمل',
    fr: 'Laissez-vous entrer',
  },
  {
    en: 'Sign In',
    id: 'Masuk',
    ar: 'تسجيل الدخول',
    fr: 'Se connecter',
  },
  {
    en: 'Sign Up',
    id: 'Daftar',
    ar: 'سجل',
    fr: "S'inscrire",
  },
  {
    en: 'Welcome Back!',
    id: 'Selamat Datang kembali!',
    ar: 'مرحبا بعودتك!',
    fr: 'Bienvenue de retour!',
  },
  {
    en: 'Sign in to continue',
    id: 'Masuk untuk melanjutkan',
    ar: 'سجل للمتابعة',
    fr: 'Connectez-vous pour continuer',
  },
  {
    en: 'Don’t have an account?',
    id: 'Belum punya akun?',
    ar: 'ليس لديك حساب؟',
    fr: "Vous n'avez pas de compte?",
  },
  {
    en: 'Need help?',
    id: 'Butuh bantuan?',
    ar: 'تحتاج مساعدة؟',
    fr: 'Besoin d’aide?',
  },
  {
    en: 'Contact Us',
    id: 'Hubungi kami',
    ar: 'اتصل بنا',
    fr: 'Contactez-nous',
  },
  {
    en: 'Continue',
    id: 'Lanjutkan',
    ar: 'استمر',
    fr: 'Continuer',
  },
  {
    en: 'Verify your phone number',
    id: 'Verifikasi nomor telepon Anda',
    ar: 'تحقق من رقم هاتفك',
    fr: 'Vérifiez votre numéro de téléphone',
  },
  {
    en: 'An 4-digit code has been sent to',
    id: 'Kode 4 digit telah dikirim ke',
    ar: 'تم إرسال رمز 4 أرقام إلى',
    fr: 'Un code à 4 chiffres a été envoyé à',
  },
  {
    en: 'The OTP will be expired in',
    id: 'OTP akan kedaluwarsa pada',
    ar: 'ستنتهي صلاحية OTP في',
    fr: 'Le OTP expirera dans',
  },
  {
    en: 'Didn’t receive the code?',
    id: 'Tidak menerima kode?',
    ar: 'لم تتلق رمز؟',
    fr: 'Vous n’avez pas reçu le code?',
  },
  {
    en: 'Resend',
    id: 'Kirim ulang',
    ar: 'إعادة إرسال',
    fr: 'Renvoyer',
  },
  {
    en: 'Verify',
    id: 'Verifikasi',
    ar: 'تحقق',
    fr: 'Vérifier',
  },
  {
    en: 'Seems like this code isn’t valid',
    id: 'Sepertinya kode ini tidak valid',
    ar: 'يبدو أن هذا الرمز غير صالح',
    fr: 'Il semble que ce code ne soit pas valide',
  },
  {
    en: 'Getting Started',
    id: 'Memulai',
    ar: 'البدء',
    fr: 'Commencer',
  },
  {
    en: 'Create an account to continue!',
    id: 'Buat akun untuk melanjutkan!',
    ar: 'إنشاء حساب للمتابعة!',
    fr: 'Créez un compte pour continuer!',
  },
  {
    en: 'Full Name',
    id: 'Nama Lengkap',
    ar: 'الاسم الكامل',
    fr: 'Nom complet',
  },
  {
    en: 'Email',
    id: 'Email',
    ar: 'البريد الإلكتروني',
    fr: 'Email',
  },
  {
    en: 'Phone Number',
    id: 'Nomor Telepon',
    ar: 'رقم الهاتف',
    fr: 'Numéro de téléphone',
  },
  {
    en: 'Already have an account?',
    id: 'Sudah punya akun?',
    ar: 'هل لديك حساب؟',
    fr: 'Vous avez déjà un compte?',
  },
  {
    en: 'Home',
    id: 'Beranda',
    ar: 'الرئيسية',
    fr: 'Accueil',
  },
  {
    en: 'Order',
    id: 'Pesanan',
    ar: 'طلبات',
    fr: 'Ordre',
  },
  {
    en: 'Earning',
    id: 'Hasil',
    fr: 'Gagner',
    ar: 'الأرباح',
  },
  {
    en: 'Chat',
    id: 'Obrolan',
    ar: 'دردشة',
    fr: 'Bavarder',
  },
  {
    en: 'Profile',
    id: 'Profil',
    ar: 'إعدادات',
    fr: 'Profil',
  },
  {
    en: 'Hayuq Driver Registration',
    id: 'Pendaftaran Driver Hayuq',
    ar: 'تسجيل سائق Hayuq',
    fr: 'Enregistrement du conducteur Hayuq',
  },
  {
    en: ' Before you become our driver, you need to fill some data for your profile. Please prepare documents:',
    id: 'Sebelum Anda menjadi driver kami, Anda perlu mengisi beberapa data untuk profil Anda. Silakan persiapkan dokumen:',
    ar: 'قبل أن تصبح سائق لدينا ، يجب عليك ملء بعض البيانات لملف تعريفك. يرجى تحضير الوثائق:',
    fr: 'Avant de devenir notre conducteur, vous devez remplir quelques données pour votre profil. Veuillez préparer les documents:',
  },
  {
    en: ' Once it’s done, our team will verify your data, and will update verification result by Email for the next step.',
    id: 'Setelah selesai, tim kami akan memverifikasi data Anda, dan akan memperbarui hasil verifikasi melalui Email untuk langkah selanjutnya.',
    ar: 'بمجرد الانتهاء من ذلك ، سيتحقق فريقنا من بياناتك ، وسيقوم بتحديث نتيجة التحقق عبر البريد الإلكتروني للخطوة التالية.',
    fr: 'Une fois terminé, notre équipe vérifiera vos données et mettra à jour le résultat de la vérification par Email pour l’étape suivante.',
  },
  {
    en: 'Go Back',
    id: 'Kembali',
    ar: 'العودة',
    fr: 'Retour',
  },
  {
    en: 'ID Card',
    id: 'KTP',
    ar: 'بطاقة الهوية',
    fr: "Carte d'identité",
  },
  {
    en: 'Driver License',
    id: 'SIM',
    ar: 'رخصة القيادة',
    fr: 'Permis de conduire',
  },
  {
    id: 'STNK',
    en: 'Vehicle Registration',
    ar: 'تسجيل السيارة',
    fr: 'Enregistrement du véhicule',
  },
  {
    id: 'SKCK',
    en: 'Police Certificate',
    ar: 'شهادة الشرطة',
    fr: 'Certificat de police',
  },
  {
    en: 'Bank Account',
    id: 'Rekening Bank',
    ar: 'حساب البنك',
    fr: 'Compte bancaire',
  },
  {
    en: 'Photo Profile',
    id: 'Photo Profil',
    ar: 'ملف الصورة',
    fr: 'Profil photographique',
  },
  {
    en: 'File',
    id: 'Berkas',
    ar: 'تحميل الملف',
    fr: 'Téléchargement de fichiers',
  },
  {
    en: 'Upload',
    id: 'Unggah',
    ar: 'ملف',
    fr: 'dossier',
  },
  {
    en: 'Please upload image in jpeg/png version from this document and information needed.',
    id: 'Unggah gambar dalam versi jpeg/png dari dokumen ini dan informasi yang dibutuhkan.',
    ar: 'يرجى تحميل الصورة في إصدار jpeg / png من هذا المستند و معلومات مطلوبة.',
    fr: 'Veuillez télécharger l`image en version jpeg/png à partir de ce document et Informations requises.',
  },
];

export default locale;
