const locale = [
  {
    en: 'Profile',
    id: 'Profil',
    fr: 'Profil',
    ar: 'الملف الشخصي',
  },
  {
    en: 'View All',
    id: 'Lihat Semua',
    fr: 'Voir tout',
    ar: 'عرض الكل',
  },
  {
    en: 'More Information',
    id: 'Informasi Lainnya',
    fr: "Plus d'informations",
    ar: 'معلومات أخرى',
  },
  {
    en: 'Sign Out',
    id: 'Keluar',
    fr: 'Se déconnecter',
    ar: 'تسجيل الخروج',
  },
  {
    en: 'Change language',
    id: 'Ganti bahasa',
    fr: 'Changer de langue',
    ar: 'تغيير اللغة',
  },
  {
    en: 'Setting',
    id: 'Pengaturan',
    fr: 'Réglage',
    ar: 'إعداد',
  },
  {
    en: 'Partnership Help Center',
    id: 'Pusat Bantuan Kerjasama',
    fr: 'Centre d’aide à la coopération',
    ar: 'مركز المساعدة للشراكة',
  },
  {
    en: 'Partnership Term & Condition',
    id: 'Syarat & Ketentuan Kerjasama',
    fr: 'Conditions générales de la coopération',
    ar: 'شروط وأحكام الشراكة',
  },
  {
    en: 'Rating History',
    id: 'Riwayat Penilaian',
    fr: 'Historique des évaluations',
    ar: 'تاريخ التقييم',
  },
  {
    en: 'Change Language',
    id: 'Ganti Bahasa',
    fr: 'Changer de langue',
    ar: 'تغيير اللغة',
  },
  {
    en: 'Change Email',
    id: 'Ganti Email',
    fr: "Changer d'email",
    ar: 'تغيير البريد الإلكتروني',
  },
  {
    en: 'Current email',
    id: 'Email saat ini',
    fr: 'Email actuel',
    ar: 'البريد الإلكتروني الحالي',
  },
  {
    en: 'New email',
    id: 'Email baru',
    fr: 'Nouvel email',
    ar: 'البريد الإلكتروني الجديد',
  },
  {
    en: 'Confirm new email',
    id: 'Konfirmasi email baru',
    fr: 'Confirmer le nouvel email',
    ar: 'تأكيد البريد الإلكتروني الجديد',
  },
  {
    en: 'Password',
    id: 'Kata sandi',
    fr: 'Mot de passe',
    ar: 'كلمة المرور',
  },
  {
    en: 'Change Phone Number',
    id: 'Ganti Nomor Telepon',
    fr: 'Changer le numéro de téléphone',
    ar: 'تغيير رقم الهاتف',
  },
  {
    en: 'Current phone number',
    id: 'Nomor telepon saat ini',
    fr: 'Numéro de téléphone actuel',
    ar: 'رقم الهاتف الحالي',
  },
  {
    en: 'New phone number',
    id: 'Nomor telepon baru',
    fr: 'Nouveau numéro de téléphone',
    ar: 'رقم هاتف جديد',
  },

  {
    en: 'Confirm new phone number',
    id: 'Konfirmasi nomor telepon baru',
    fr: 'Confirmer le nouveau numéro de téléphone',
    ar: 'تأكيد رقم الهاتف الجديد',
  },
  {
    en: 'Choose Language',
    id: 'Pilih Bahasa',
    fr: 'Choisissez la langue',
    ar: 'اختر اللغة',
  },
  {
    en: 'Account',
    id: 'Akun',
    fr: 'Compte',
    ar: 'الحساب',
  },
  {
    en: 'Change Vehicle Info',
    id: 'Ganti Info Kendaraan',
    fr: 'Changer les informations sur le véhicule',
    ar: 'تغيير معلومات المركبة',
  },
  {
    en: 'Type',
    id: 'Tipe',
    fr: 'Type',
    ar: 'نوع',
  },
  {
    en: 'Number Plate',
    id: 'Nomor Plat',
    fr: 'Plaque d’immatriculation',
    ar: 'رقم لوحة',
  },
  {
    en: 'Registration Number',
    id: 'STNK',
    fr: 'Numéro d’immatriculation',
    ar: 'رقم التسجيل',
  },
  {
    en: 'Vehicle Type',
    id: 'Tipe Kendaraan',
    fr: 'Type de véhicule',
    ar: 'نوع السيارة',
  },
  {
    en: 'Number Plate',
    id: 'Nomor Plat',
    fr: "Numéro plat",
    ar: 'رقم بلات',
  },
  {
    en: 'Save',
    id: 'Simpan',
    fr: 'Sauvegarder',
    ar: 'حفظ',
  },
  {
    en: 'New STNK Upload',
    id: 'Upload STNK Baru',
    fr: 'Nouveau numéro d’immatriculation',
    ar: 'رفع رقم التسجيل الجديد',
  },
  {
    en: 'Bank Information',
    id: 'Informasi Bank',
    fr: 'Informations bancaires',
    ar: 'معلومات البنك',
  },
  {
    en: 'Primary',
    id: 'Utama',
    fr: 'Primaire',
    ar: 'أساسي',
  },
  {
    en: 'Add new Bank Account',
    id: 'Tambah Akun Bank Baru',
    fr: 'Ajouter un nouveau compte bancaire',
    ar: 'إضافة حساب بنكي جديد',
  },
  {
    en: 'Bank Name',
    id: 'Nama Bank',
    fr: 'Nom de la banque',
    ar: 'اسم البنك',
  },
  {
    en: 'Account Number',
    id: 'Nomor Rekening',
    fr: 'Numéro de compte',
    ar: 'رقم الحساب',
  },
  {
    en: 'Save',
    id: 'Simpan',
    fr: 'Sauvegarder',
    ar: 'حفظ',
  },
  {
    en: 'Add New',
    id: 'Tambah Baru',
    fr: 'Ajouter un nouveau',
    ar: 'إضافة جديد',
  },
];

export default locale;
