require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

$RNMapboxMapsImpl = 'mapbox'
platform :ios, '13'
install! 'cocoapods', :deterministic_uuids => false

INHIBIT_WARNING_BY_DEFAULT = true

target 'hayuqdriver' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()
  
  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => true,
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => FlipperConfiguration.enabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
  pod 'CodePush', :path => '../node_modules/react-native-code-push'
  target 'hayuqdriverTests' do
    inherit! :complete
    # Pods for testing
  end
  use_native_modules!

  pre_install do |installer|
    $RNMapboxMaps.pre_install(installer)
  end
  post_install do |installer|
  $RNMapboxMaps.pre_install(installer)
  react_native_post_install(installer)
  __apply_Xcode_12_5_M1_post_install_workaround(installer)
  # Add these lines for Xcode 14 builds
  installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings["DEVELOPMENT_TEAM"] = "35H3B8HH46"
        end
    end
  end
end
end
